name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Accept Android licenses
        run: yes | sdkmanager --licenses
      
      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer -v android debug
          workdir: .
      
      - uses: actions/upload-artifact@v4
        with:
          name: Hesabu-App-APK
          path: bin/*.apk
